#!/usr/bin/env python3
"""Generate the PRISM's STEW decode from the chroma compiler's config.

The compiler config (tinyqv32.cfg) is the one description of where each
STEW field sits in the 128-bit word; this script writes the matching
Verilog assigns into prism.v between the STEW MAP markers so the RTL cannot
drift from the bitstreams.

    python3 stew_map.py tinyqv32.cfg ../src/user_peripherals/prism/prism.v

Field order in the config (and what the RTL calls it):
    inc            -> inc_si[f]
    mux            -> input_mux_sel[f][m], muxes.count fields of muxes.size bits
    jmp #0, #1     -> jump_to[f][0] (tree0), jump_to[f][1] (tree1)
    out #0, #1, #2 -> jump_outputs[f][0], jump_outputs[f][1], state_outputs[f]
    cfg #0, #1     -> cmp_sel[f][0], cmp_sel[f][1]   (LUT3 tables)
    cfg #2, #3     -> cond_cfg[f][0], cond_cfg[f][1] (LUT2 tables)
"""
import re
import sys

BEGIN = "// ---- BEGIN STEW MAP"
END = "// ---- END STEW MAP ----"


def strip_comments(text):
    return "\n".join(line.split("#", 1)[0] for line in text.splitlines())


def parse_items(cfg_text):
    text = strip_comments(cfg_text)
    m = re.search(r"muxes\s*:\s*\{([^}]*)\}", text)
    muxes = dict(re.findall(r"(\w+)\s*:\s*(\d+)", m.group(1)))
    mux_size, mux_count = int(muxes["size"]), int(muxes["count"])

    stew = text[text.index("stew"):]
    size = int(re.search(r"size\s*:\s*(\d+)", stew).group(1))
    items_text = stew[stew.index("items"):]
    items_text = items_text[items_text.index("[") + 1:]
    items = []
    depth, start = 0, None
    for i, ch in enumerate(items_text):
        if ch == "{":
            if depth == 0:
                start = i
            depth += 1
        elif ch == "}":
            depth -= 1
            if depth == 0:
                items.append(items_text[start + 1:i])
        elif ch == "]" and depth == 0:
            break
    fields = []
    for body in items:
        typ = re.search(r'type\s*:\s*"(\w+)"', body).group(1)
        bits = re.search(r"bits\s*:\s*\[([^\]]*)\]", body)
        if bits:
            pos = [int(x) for x in bits.group(1).replace(",", " ").split()]
        else:
            off = int(re.search(r"offset\s*:\s*(\d+)", body).group(1))
            n = int(re.search(r"size\s*:\s*(\d+)", body).group(1))
            pos = list(range(off, off + n))
        fields.append((typ, pos))
    return size, mux_size, mux_count, fields


def vexpr(pos):
    """Verilog expression for a field whose logical bit i is STEW bit pos[i]."""
    if pos == list(range(pos[0], pos[0] + len(pos))):
        if len(pos) == 1:
            return "stew[f][%d]" % pos[0]
        return "stew[f][%d:%d]" % (pos[-1], pos[0])
    return "{" + ", ".join("stew[f][%d]" % p for p in reversed(pos)) + "}"


def generate(cfg_path):
    size, mux_size, mux_count, fields = parse_items(open(cfg_path).read())
    by = {}
    for typ, pos in fields:
        by.setdefault(typ, []).append(pos)
    assert len(by["inc"]) == 1 and len(by["inc"][0]) == 1
    assert len(by["mux"]) == 1 and len(by["mux"][0]) == mux_size * mux_count
    assert len(by["jmp"]) == 2 and len(by["out"]) == 3 and len(by["cfg"]) == 4
    used = sorted(p for _, pos in fields for p in pos)
    assert used == list(range(size)), "STEW bits used more than once or unused: %s" % (
        sorted(set(range(size)) ^ set(used)))

    lines = []
    lines.append("      %s (generated by chromas/stew_map.py from chromas/%s; edit the config, then `make stew-map`) ----"
                 % (BEGIN, cfg_path.split("/")[-1]))
    lines.append("      // %d-bit STEW: %d input muxes of %d bits, 2 jump targets, 3 x %d outputs, LUT tables %s"
                 % (size, mux_count, mux_size, len(by["out"][0]), ", ".join(str(len(p)) for p in by["cfg"])))
    lines.append("      assign inc_si[f]           = %s;" % vexpr(by["inc"][0]))
    mux = by["mux"][0]
    for m in range(mux_count):
        lines.append("      assign input_mux_sel[f][%d] = %s;" % (m, vexpr(mux[m * mux_size:(m + 1) * mux_size])))
    for cmp in range(2):
        lines.append("      assign jump_to[f][%d]       = %s;   // tree%d jump target" % (cmp, vexpr(by["jmp"][cmp]), cmp))
    for cmp in range(2):
        lines.append("      assign jump_outputs[f][%d]  = %s;   // tree%d transition outputs, out 20..0"
                     % (cmp, vexpr(by["out"][cmp]), cmp))
    lines.append("      assign state_outputs[f]    = %s;   // default outputs, out 20..0" % vexpr(by["out"][2]))
    for cmp in range(2):
        lines.append("      assign cmp_sel[f][%d]       = %s;   // tree%d LUT3" % (cmp, vexpr(by["cfg"][cmp]), cmp))
    for c in range(2):
        lines.append("      assign cond_cfg[f][%d]      = %s;   // cond%d LUT2" % (c, vexpr(by["cfg"][2 + c]), c))
    lines.append("      %s" % END)
    return "\n".join(lines) + "\n"


def main():
    cfg_path, rtl_path = sys.argv[1], sys.argv[2]
    block = generate(cfg_path)
    rtl = open(rtl_path).read()
    b = rtl.index(BEGIN)
    b = rtl.rindex("\n", 0, b) + 1
    e = rtl.index(END) + len(END)
    e = rtl.index("\n", e) + 1
    new = rtl[:b] + block + rtl[e:]
    if new != rtl:
        open(rtl_path, "w").write(new)
        print("%s: STEW map updated" % rtl_path)
    else:
        print("%s: STEW map unchanged" % rtl_path)


if __name__ == "__main__":
    main()
